Controllers/EmployeesController.cs
using HMS_web.Data;
using HMS_web.Models;
using HMS_web.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HMS_web.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly MVCDBContext mvcDBContext;
        public EmployeesController(MVCDBContext mvcDBContext)
        {
            this.mvcDBContext = mvcDBContext;
        }
        public async Task<IActionResult> Index()
        {
            var employees = await mvcDBContext.Employees.ToListAsync();
            return View(employees);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Add(AddEmployees addEmployeesRequest)
        {
            var employees = new Employee()
            {
                Id = Guid.NewGuid(),
                EmployeeType = addEmployeesRequest.EmployeeType,
                Name = addEmployeesRequest.Name,
                Surname = addEmployeesRequest.Surname,
                Phone = addEmployeesRequest.Phone,
                Email = addEmployeesRequest.Email,
                MaritalStatus = addEmployeesRequest.MaritalStatus,
                DOB = addEmployeesRequest.DOB,
                Address = addEmployeesRequest.Address,
            };
            await mvcDBContext.Employees.AddAsync(employees);
            await mvcDBContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var employee = await mvcDBContext.Employees.FirstOrDefaultAsync(x => x.Id == id);

            if(employee == null)
            {
                var viewModel = new UpdateEmployee()
                {
                    EmployeeType = employee.EmployeeType,
                    Name = employee.Name,
                    Surname = employee.Surname,
                    Phone = employee.Phone,
                    Email = employee.Email,
                    MaritalStatus = employee.MaritalStatus,
                    DOB = employee.DOB,
                    Address = employee.Address,
                };
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/PatientsController.cs
using HMS_web.Data;
using HMS_web.Models.Domain;
using HMS_web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HMS_web.Controllers
{
    public class PatientsController : Controller
    {
        private readonly MVCDBContext mvcDBContext;
        public PatientsController(MVCDBContext mvcDBContext)
        {
            this.mvcDBContext = mvcDBContext;
        }
        public async Task<IActionResult> Index()
        {
            var patient = await mvcDBContext.Patients.ToListAsync();
            return View(patient);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddPatients addPatientsRequest)
        {
            var patients = new Patients()
            {
                Id = Guid.NewGuid(),
                Name = addPatientsRequest.Name,
                Surname = addPatientsRequest.Surname,
                Phone = addPatientsRequest.Phone,
                Email = addPatientsRequest.Email,
                MaritalStatus = addPatientsRequest.MaritalStatus,
                DOB = addPatientsRequest.DOB,
                Address = addPatientsRequest.Address,
            };
            await mvcDBContext.Patients.AddAsync(patients);
            await mvcDBContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var patients = await mvcDBContext.Patients.FirstOrDefaultAsync(x => x.Id == id);

            if (patients == null)
            {
                var viewModel = new UpdatePatients()
                {
                    Name = patients.Name,
                    Surname = patients.Surname,
                    Phone = patients.Phone,
                    Email = patients.Email,
                    MaritalStatus = patients.MaritalStatus,
                    DOB = patients.DOB,
                    Address = patients.Address,
                };
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HMS_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HMS_web.styles.css" asp-append-version="true" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
</head>
<body>
    <div class="row">
        <div class="col">
            <div class="side-menu">

                <nav class="navbar navbar-default" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <div class="brand-wrapper">
                            <!-- Hamburger -->
                            <button type="button" class="navbar-toggle">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                            <!-- Brand -->
                            <div class="brand-name-wrapper">
                                <a class="navbar-brand" href="#">
                                    Brand
                                </a>
                            </div>
                        </div>

                    </div>

                    <!-- Main Menu -->
                    <div class="side-menu-container">
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-send"></span>Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Employees" asp-action="Add"><span class="glyphicon glyphicon-send"></span>Add Employees</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Employees" asp-action="Index"><span class="glyphicon glyphicon-send"></span>Employees</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Patients" asp-action="Add"><span class="glyphicon glyphicon-send"></span>Add Patients</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Patients" asp-action="Index"><span class="glyphicon glyphicon-send"></span>Patients</a>
                            </li>
                        </ul>

                    </div><!-- /.navbar-collapse -->
                </nav>
            </div>
        </div>
        <div class="col-md-8">
            <div class="main">
                <div class="side-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
   @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HMS_web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)*@
</body>
</html>

Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HMS_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HMS_web.styles.css" asp-append-version="true" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
    <div class="row">
        <!-- uncomment code for absolute positioning tweek see top comment in css -->
        <!-- <div class="absolute-wrapper"> </div> -->
        <!-- Menu -->
        <div class="side-menu">

            <nav class="navbar navbar-default" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <div class="brand-wrapper">
                        <!-- Hamburger -->
                        <button type="button" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <!-- Brand -->
                        <div class="brand-name-wrapper">
                            <a class="navbar-brand" href="#">
                                Brand
                            </a>
                        </div>

                        <!-- Search -->
                        <a data-toggle="collapse" href="#search" class="btn btn-default" id="search-trigger">
                            <span class="glyphicon glyphicon-search"></span>
                        </a>

                        <!-- Search body -->
                        <div id="search" class="panel-collapse collapse">
                            <div class="panel-body">
                                <form class="navbar-form" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                    </div>
                                    <button type="submit" class="btn btn-default "><span class="glyphicon glyphicon-ok"></span></button>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>

                <!-- Main Menu -->
                <div class="side-menu-container">
                    <ul class="nav navbar-nav">

                        <li><a href="#"><span class="glyphicon glyphicon-send"></span> Link</a></li>
                        <li class="active"><a href="#"><span class="glyphicon glyphicon-plane"></span> Active Link</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-cloud"></span> Link</a></li>

                        <!-- Dropdown-->
                        <li class="panel panel-default" id="dropdown">
                            <a data-toggle="collapse" href="#dropdown-lvl1">
                                <span class="glyphicon glyphicon-user"></span> Sub Level <span class="caret"></span>
                            </a>

                            <!-- Dropdown level 1 -->
                            <div id="dropdown-lvl1" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul class="nav navbar-nav">
                                        <li><a href="#">Link</a></li>
                                        <li><a href="#">Link</a></li>
                                        <li><a href="#">Link</a></li>

                                        <!-- Dropdown level 2 -->
                                        <li class="panel panel-default" id="dropdown">
                                            <a data-toggle="collapse" href="#dropdown-lvl2">
                                                <span class="glyphicon glyphicon-off"></span> Sub Level <span class="caret"></span>
                                            </a>
                                            <div id="dropdown-lvl2" class="panel-collapse collapse">
                                                <div class="panel-body">
                                                    <ul class="nav navbar-nav">
                                                        <li><a href="#">Link</a></li>
                                                        <li><a href="#">Link</a></li>
                                                        <li><a href="#">Link</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>

                        <li><a href="#"><span class="glyphicon glyphicon-signal"></span> Link</a></li>

                    </ul>
                </div><!-- /.navbar-collapse -->
            </nav>
        </div>
        <div class="container-fluid">
            <div class="side-body">
                @RenderBody()
            </div>
        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HMS_web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>